# This is for local development, you can use this docker-compose file to run both the backend and frontend services together.
version: '3.8'

services:
  backend:
    image: pickus-backend:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file: backend/.env

  frontend:
    image: pickus-frontend:latest
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    env_file: frontend/.env
    depends_on:
      - backend
    # # Uncomment the 2 lines below if you want the output to include a QR code to scan with your phone
    # stdin_open: true
    # tty: true
