export enum RideIrrelevantReason {
  RIDE_CANCELLED = 'RIDE_CANCELLED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  RIDE_TIME_PASSED = 'RIDE_TIME_PASSED',
  RIDE_FULL = 'RIDE_FULL',
  RIDE_NOT_FOUND = 'RIDE_NOT_FOUND',
  RIDE_ACTIVE = 'RIDE_ACTIVE',
}
